/**
 * Encryption Utilities
 *
 * Provides cryptographic utilities for sign-to-derive key derivation
 * and AES-256-GCM client-side encryption/decryption.
 *
 * Uses SHA-256 for key derivation (matching the Go/SiYuan client).
 * All encryption/decryption happens client-side via WebCrypto —
 * the server never sees plaintext property values.
 */

import { x25519 } from '@noble/curves/ed25519';
import { sha256, keccak256, hexToBytes } from 'viem';

// ── Constants ────────────────────────────────────────────────────────────

const CENC_PREFIX = "__cenc_v1_";
const CENC_GROUP_PREFIX = "__cenc_v2_group_";
const NONCE_BYTES = 12;
const GROUP_KEY_BYTES = 32;
const GROUP_WRAP_SALT_BYTES = 16;
const X25519_KEY_BYTES = 32;
const GROUP_WRAP_ALG = "X25519-HKDF-SHA256-AES-256-GCM";
const GROUP_WRAP_INFO = "kfdb-shared-notebook-group-key-v1";

// ── Type Tags (must match Rust-side deserialization) ─────────────────────

type TypeTag = "str" | "int" | "float" | "bool" | "null" | "arr" | "obj";

export interface SharingKeyPair {
  algorithm: "X25519";
  /** Base64-encoded 32-byte X25519 public key. Safe to send to KFDB. */
  publicKey: string;
  /** Base64-encoded 32-byte X25519 private key. Keep client-side only. */
  privateKey: string;
}

export interface WrappedGroupKey {
  version: 1;
  alg: typeof GROUP_WRAP_ALG;
  /** Base64-encoded ephemeral X25519 public key generated by the sender. */
  ephemeral_public_key: string;
  /** Base64-encoded HKDF salt. */
  salt: string;
  /** Base64-encoded AES-GCM nonce. */
  nonce: string;
  /** Base64-encoded AES-GCM ciphertext wrapping the 32-byte group key. */
  ciphertext: string;
}

// ── Key Derivation ───────────────────────────────────────────────────────

/**
 * Returns a deterministic message for sign-to-derive key derivation.
 *
 * The wallet address parameter is kept for backward compatibility but
 * the message MUST be deterministic — the same signature always produces
 * the same encryption key.
 *
 * @param _walletAddress - User's wallet address (kept for compat, unused)
 * @returns Fixed message to sign
 */
export function getDeriveKeyMessage(_walletAddress: string): string {
  return "KFDB Encryption Key\nVersion: 1\nChain: 8453";
}

/**
 * Derives an encryption key from an Ethereum signature using SHA-256.
 *
 * This enables true user-controlled encryption:
 * - User signs a deterministic message with their wallet
 * - Signature is used to derive the encryption key
 * - Only the user can encrypt/decrypt (operator cannot read)
 *
 * Uses SHA-256 hash of the signature to derive a 32-byte key.
 * This matches the Go client (SiYuan) for cross-client interop.
 *
 * @param signature - Ethereum signature (65 bytes: r, s, v)
 * @returns Hex string of the derived key (32 bytes)
 */
export function deriveKeyFromSignature(signature: string): string {
  return deriveKeyFromSignatureBytes(signature, sha256);
}

/**
 * Legacy key derivation using keccak256.
 *
 * Use this only to decrypt data encrypted with keys derived before
 * the SHA-256 migration. New code should use deriveKeyFromSignature().
 *
 * @param signature - Ethereum signature (65 bytes: r, s, v)
 * @returns Hex string of the derived key (32 bytes)
 */
export function deriveKeyFromSignatureLegacy(signature: string): string {
  return deriveKeyFromSignatureBytes(signature, keccak256);
}

/** Shared implementation for key derivation with pluggable hash function. */
function deriveKeyFromSignatureBytes(
  signature: string,
  hashFn: (bytes: Uint8Array) => string,
): string {
  const normalizedSig = signature.startsWith('0x') ? signature.slice(2) : signature;

  if (normalizedSig.length !== 130) {
    throw new Error('Invalid signature length: expected 65 bytes (130 hex chars)');
  }

  const r = normalizedSig.slice(0, 64);
  const s = normalizedSig.slice(64, 128);
  const v = normalizedSig.slice(128, 130);

  const rBytes = hexToBytes(`0x${r}`);
  const sBytes = hexToBytes(`0x${s}`);
  const vBytes = hexToBytes(`0x${v}`);
  const signatureBytes = new Uint8Array(rBytes.length + sBytes.length + vBytes.length);
  signatureBytes.set(rBytes, 0);
  signatureBytes.set(sBytes, rBytes.length);
  signatureBytes.set(vBytes, rBytes.length + sBytes.length);

  return hashFn(signatureBytes);
}

/**
 * Imports a derived key hex string as a WebCrypto CryptoKey for AES-256-GCM.
 *
 * @param hexKey - 32-byte hex key from deriveKeyFromSignature (with or without 0x prefix)
 * @returns CryptoKey suitable for encryptValue/decryptValue
 */
export async function importKeyFromHex(hexKey: string): Promise<CryptoKey> {
  const hex = hexKey.startsWith('0x') ? hexKey.slice(2) : hexKey;
  if (hex.length !== 64) {
    throw new Error('Invalid key length: expected 32 bytes (64 hex chars)');
  }
  const keyBytes = new Uint8Array(hex.match(/.{2}/g)!.map(b => parseInt(b, 16)));
  return crypto.subtle.importKey(
    "raw",
    keyBytes,
    { name: "AES-GCM" },
    false,
    ["encrypt", "decrypt"],
  );
}

// ── Type Classification & Serialization ──────────────────────────────────

function classifyValue(value: unknown): TypeTag {
  if (value === null || value === undefined) return "null";
  if (typeof value === "string") return "str";
  if (typeof value === "number") {
    return Number.isInteger(value) ? "int" : "float";
  }
  if (typeof value === "boolean") return "bool";
  if (Array.isArray(value)) return "arr";
  return "obj";
}

function serializeValue(tag: TypeTag, value: unknown): Uint8Array {
  switch (tag) {
    case "str":
      return new TextEncoder().encode(value as string);
    case "int": {
      const buf = new ArrayBuffer(8);
      new DataView(buf).setBigInt64(0, BigInt(value as number), true);
      return new Uint8Array(buf);
    }
    case "float": {
      const buf = new ArrayBuffer(8);
      new DataView(buf).setFloat64(0, value as number, true);
      return new Uint8Array(buf);
    }
    case "bool":
      return new Uint8Array([(value as boolean) ? 1 : 0]);
    case "null":
      return new Uint8Array(0);
    case "arr":
    case "obj":
      return new TextEncoder().encode(JSON.stringify(value));
  }
}

function deserializeValue(tag: TypeTag, bytes: Uint8Array): unknown {
  switch (tag) {
    case "str":
      return new TextDecoder().decode(bytes);
    case "int":
      return Number(new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength).getBigInt64(0, true));
    case "float":
      return new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength).getFloat64(0, true);
    case "bool":
      return bytes[0] === 1;
    case "null":
      return null;
    case "arr":
    case "obj":
      return JSON.parse(new TextDecoder().decode(bytes));
  }
}

// ── Base64 Helpers ───────────────────────────────────────────────────────

function toBase64(bytes: Uint8Array): string {
  let binary = "";
  for (let i = 0; i < bytes.length; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary);
}

function fromBase64(b64: string): Uint8Array {
  const binary = atob(b64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

function asBufferSource(bytes: Uint8Array): BufferSource {
  return bytes as unknown as BufferSource;
}

function normalizeBase64OrBytes(value: string | Uint8Array, expectedBytes: number, label: string): Uint8Array {
  const bytes = typeof value === "string" ? fromBase64(value) : value;
  if (bytes.length !== expectedBytes) {
    throw new Error(`Invalid ${label} length: expected ${expectedBytes} bytes`);
  }
  return bytes;
}

async function importAesGcmKey(rawKey: Uint8Array): Promise<CryptoKey> {
  if (rawKey.length !== GROUP_KEY_BYTES) {
    throw new Error(`Invalid AES-GCM key length: expected ${GROUP_KEY_BYTES} bytes`);
  }
  return crypto.subtle.importKey(
    "raw",
    asBufferSource(rawKey),
    { name: "AES-GCM" },
    false,
    ["encrypt", "decrypt"],
  );
}

async function deriveGroupWrapKey(
  sharedSecret: Uint8Array,
  salt: Uint8Array,
): Promise<CryptoKey> {
  const hkdfKey = await crypto.subtle.importKey(
    "raw",
    asBufferSource(sharedSecret),
    "HKDF",
    false,
    ["deriveKey"],
  );
  return crypto.subtle.deriveKey(
    {
      name: "HKDF",
      hash: "SHA-256",
      salt: asBufferSource(salt),
      info: asBufferSource(new TextEncoder().encode(GROUP_WRAP_INFO)),
    },
    hkdfKey,
    { name: "AES-GCM", length: 256 },
    false,
    ["encrypt", "decrypt"],
  );
}

// ── Shared Notebook Group Key Helpers ───────────────────────────────────

/**
 * Generate a long-lived X25519 sharing keypair.
 *
 * The public key is enrolled with KFDB so other clients can wrap notebook
 * group keys for this recipient. The private key must remain client-side.
 */
export function generateSharingKeyPair(): SharingKeyPair {
  const privateKey = x25519.utils.randomPrivateKey();
  const publicKey = x25519.getPublicKey(privateKey);
  return {
    algorithm: "X25519",
    publicKey: toBase64(publicKey),
    privateKey: toBase64(privateKey),
  };
}

/** Generate a random 32-byte AES group key for shared notebook fields. */
export function generateSharedNotebookGroupKey(): string {
  return toBase64(crypto.getRandomValues(new Uint8Array(GROUP_KEY_BYTES)));
}

/** Import a base64 or raw 32-byte group key for AES-256-GCM field encryption. */
export async function importSharedNotebookGroupKey(groupKey: string | Uint8Array): Promise<CryptoKey> {
  return importAesGcmKey(normalizeBase64OrBytes(groupKey, GROUP_KEY_BYTES, "group key"));
}

/**
 * Wrap a shared notebook group key to a recipient's X25519 public key.
 *
 * Uses ephemeral-static X25519, HKDF-SHA256, then AES-256-GCM over the raw
 * 32-byte group key. The returned blob is safe to store in KFDB.
 */
export async function wrapSharedNotebookGroupKey(
  groupKey: string | Uint8Array,
  recipientPublicKey: string | Uint8Array,
): Promise<WrappedGroupKey> {
  const rawGroupKey = normalizeBase64OrBytes(groupKey, GROUP_KEY_BYTES, "group key");
  const recipientPk = normalizeBase64OrBytes(recipientPublicKey, X25519_KEY_BYTES, "recipient public key");
  const ephemeralPrivateKey = x25519.utils.randomPrivateKey();
  const ephemeralPublicKey = x25519.getPublicKey(ephemeralPrivateKey);
  const sharedSecret = x25519.getSharedSecret(ephemeralPrivateKey, recipientPk);
  const salt = crypto.getRandomValues(new Uint8Array(GROUP_WRAP_SALT_BYTES));
  const nonce = crypto.getRandomValues(new Uint8Array(NONCE_BYTES));
  const wrapKey = await deriveGroupWrapKey(sharedSecret, salt);

  const ciphertext = await crypto.subtle.encrypt(
    { name: "AES-GCM", iv: asBufferSource(nonce) },
    wrapKey,
    asBufferSource(rawGroupKey),
  );

  return {
    version: 1,
    alg: GROUP_WRAP_ALG,
    ephemeral_public_key: toBase64(ephemeralPublicKey),
    salt: toBase64(salt),
    nonce: toBase64(nonce),
    ciphertext: toBase64(new Uint8Array(ciphertext)),
  };
}

/**
 * Unwrap a shared notebook group key with the recipient's X25519 private key.
 *
 * Throws if the private key is not the intended recipient or the wrap blob was
 * modified.
 */
export async function unwrapSharedNotebookGroupKey(
  wrapped: WrappedGroupKey,
  recipientPrivateKey: string | Uint8Array,
): Promise<string> {
  if (wrapped.version !== 1 || wrapped.alg !== GROUP_WRAP_ALG) {
    throw new Error("Unsupported wrapped group key format");
  }
  const privateKey = normalizeBase64OrBytes(recipientPrivateKey, X25519_KEY_BYTES, "recipient private key");
  const ephemeralPk = normalizeBase64OrBytes(wrapped.ephemeral_public_key, X25519_KEY_BYTES, "ephemeral public key");
  const salt = normalizeBase64OrBytes(wrapped.salt, GROUP_WRAP_SALT_BYTES, "wrap salt");
  const nonce = normalizeBase64OrBytes(wrapped.nonce, NONCE_BYTES, "wrap nonce");
  const ciphertext = fromBase64(wrapped.ciphertext);
  const sharedSecret = x25519.getSharedSecret(privateKey, ephemeralPk);
  const wrapKey = await deriveGroupWrapKey(sharedSecret, salt);

  const plaintext = await crypto.subtle.decrypt(
    { name: "AES-GCM", iv: asBufferSource(nonce) },
    wrapKey,
    asBufferSource(ciphertext),
  );
  return toBase64(new Uint8Array(plaintext));
}

function validateGroupKeyId(keyId: string): void {
  if (!/^[A-Za-z0-9_-]+$/.test(keyId)) {
    throw new Error("Invalid group key id: expected URL-safe base64/id characters");
  }
}

function parseGroupEncryptedValue(encoded: string): { keyId: string; tag: TypeTag; b64: string } {
  if (!encoded.startsWith(CENC_GROUP_PREFIX)) {
    throw new Error("Not a group client-encrypted value");
  }

  const rest = encoded.slice(CENC_GROUP_PREFIX.length);
  const dotIdx = rest.indexOf(".");
  const colonIdx = rest.indexOf(":");
  if (dotIdx <= 0 || colonIdx <= dotIdx + 1) {
    throw new Error("Invalid group cenc format");
  }

  return {
    keyId: rest.slice(0, dotIdx),
    tag: rest.slice(dotIdx + 1, colonIdx) as TypeTag,
    b64: rest.slice(colonIdx + 1),
  };
}

/**
 * Encrypt one field with a shared notebook group key.
 *
 * Wire format: `__cenc_v2_group_{keyId}.{type}:{base64(nonce || ciphertext || tag)}`.
 */
export async function encryptSharedNotebookField(
  groupKey: CryptoKey | string | Uint8Array,
  value: unknown,
  keyId = "k1",
): Promise<string> {
  validateGroupKeyId(keyId);
  const key = groupKey instanceof CryptoKey ? groupKey : await importSharedNotebookGroupKey(groupKey);
  const tag = classifyValue(value);
  const plaintext = serializeValue(tag, value);
  const nonce = crypto.getRandomValues(new Uint8Array(NONCE_BYTES));

  const ciphertext = await crypto.subtle.encrypt(
    { name: "AES-GCM", iv: asBufferSource(nonce) },
    key,
    asBufferSource(plaintext),
  );

  const combined = new Uint8Array(NONCE_BYTES + ciphertext.byteLength);
  combined.set(nonce, 0);
  combined.set(new Uint8Array(ciphertext), NONCE_BYTES);

  return `${CENC_GROUP_PREFIX}${keyId}.${tag}:${toBase64(combined)}`;
}

/** Decrypt a `__cenc_v2_group_` field with its shared notebook group key. */
export async function decryptSharedNotebookField(
  groupKey: CryptoKey | string | Uint8Array,
  encoded: string,
): Promise<unknown> {
  const key = groupKey instanceof CryptoKey ? groupKey : await importSharedNotebookGroupKey(groupKey);
  const parsed = parseGroupEncryptedValue(encoded);
  const combined = fromBase64(parsed.b64);

  if (combined.length < NONCE_BYTES) {
    throw new Error("Invalid group cenc format: data too short");
  }

  const nonce = combined.slice(0, NONCE_BYTES);
  const ciphertextWithTag = combined.slice(NONCE_BYTES);
  const plaintext = await crypto.subtle.decrypt(
    { name: "AES-GCM", iv: asBufferSource(nonce) },
    key,
    asBufferSource(ciphertextWithTag),
  );

  return deserializeValue(parsed.tag, new Uint8Array(plaintext));
}

/** Encrypt all properties with a shared notebook group key. */
export async function encryptSharedNotebookFields(
  groupKey: CryptoKey | string | Uint8Array,
  props: Record<string, unknown>,
  keyId = "k1",
): Promise<Record<string, unknown>> {
  const key = groupKey instanceof CryptoKey ? groupKey : await importSharedNotebookGroupKey(groupKey);
  const result: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(props)) {
    const encrypted = await encryptSharedNotebookField(key, extractTypedValue(v), keyId);
    result[k] = { String: encrypted };
  }
  return result;
}

/** Decrypt any `__cenc_v2_group_` values found in response rows. */
export async function decryptSharedNotebookRows(
  groupKeys: Record<string, CryptoKey | string | Uint8Array>,
  rows: Record<string, unknown>[],
): Promise<Record<string, unknown>[]> {
  const imported = new Map<string, CryptoKey>();
  async function keyFor(keyId: string): Promise<CryptoKey> {
    const existing = imported.get(keyId);
    if (existing) return existing;
    const key = groupKeys[keyId];
    if (!key) throw new Error(`Missing shared notebook group key: ${keyId}`);
    const importedKey = key instanceof CryptoKey ? key : await importSharedNotebookGroupKey(key);
    imported.set(keyId, importedKey);
    return importedKey;
  }

  const decrypted: Record<string, unknown>[] = [];
  for (const row of rows) {
    const newRow: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(row)) {
      const raw = extractTypedValue(v);
      if (typeof raw === "string" && raw.startsWith(CENC_GROUP_PREFIX)) {
        const { keyId } = parseGroupEncryptedValue(raw);
        newRow[k] = await decryptSharedNotebookField(await keyFor(keyId), raw);
      } else {
        newRow[k] = v;
      }
    }
    decrypted.push(newRow);
  }
  return decrypted;
}

// ── Encrypt / Decrypt ────────────────────────────────────────────────────

/**
 * Encrypt a single value with AES-256-GCM.
 * Returns wire format: "__cenc_v1_{type}:{base64(nonce || ciphertext || tag)}"
 */
export async function encryptValue(key: CryptoKey, value: unknown): Promise<string> {
  const tag = classifyValue(value);
  const plaintext = serializeValue(tag, value);
  const nonce = crypto.getRandomValues(new Uint8Array(NONCE_BYTES));

  const ciphertext = await crypto.subtle.encrypt(
    { name: "AES-GCM", iv: nonce },
    key,
    new Uint8Array(plaintext) as unknown as ArrayBuffer,
  );

  // Concat nonce + ciphertext (WebCrypto appends 16-byte auth tag to ciphertext)
  const combined = new Uint8Array(NONCE_BYTES + ciphertext.byteLength);
  combined.set(nonce, 0);
  combined.set(new Uint8Array(ciphertext), NONCE_BYTES);

  return `${CENC_PREFIX}${tag}:${toBase64(combined)}`;
}

/**
 * Decrypt a __cenc_v1_ encoded string back to its original value.
 */
export async function decryptValue(key: CryptoKey, encoded: string): Promise<unknown> {
  if (!encoded.startsWith(CENC_PREFIX)) {
    throw new Error("Not a client-encrypted value");
  }

  const rest = encoded.slice(CENC_PREFIX.length);
  const colonIdx = rest.indexOf(":");
  if (colonIdx === -1) {
    throw new Error("Invalid cenc format: missing type tag");
  }

  const tag = rest.slice(0, colonIdx) as TypeTag;
  const b64 = rest.slice(colonIdx + 1);
  const combined = fromBase64(b64);

  if (combined.length < NONCE_BYTES) {
    throw new Error("Invalid cenc format: data too short");
  }

  const nonce = combined.slice(0, NONCE_BYTES);
  const ciphertextWithTag = combined.slice(NONCE_BYTES);

  const plaintext = await crypto.subtle.decrypt(
    { name: "AES-GCM", iv: nonce },
    key,
    ciphertextWithTag,
  );

  return deserializeValue(tag, new Uint8Array(plaintext));
}

// ── KFDB Property Helpers ────────────────────────────────────────────────

/**
 * Extract the raw value from a KFDB typed property wrapper.
 * e.g. {"String": "hello"} -> "hello", {"Integer": 42} -> 42
 */
function extractTypedValue(v: unknown): unknown {
  if (v && typeof v === "object" && !Array.isArray(v)) {
    const obj = v as Record<string, unknown>;
    if ("String" in obj) return obj.String;
    if ("Integer" in obj) return obj.Integer;
    if ("Float" in obj) return obj.Float;
    if ("Boolean" in obj) return obj.Boolean;
  }
  return v;
}

/**
 * Encrypt all property values in a properties object.
 * Each value is encrypted and wrapped in a KFDB String type wrapper,
 * since all ciphertext is stored as strings.
 */
export async function encryptProperties(
  key: CryptoKey,
  props: Record<string, unknown>,
): Promise<Record<string, unknown>> {
  const result: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(props)) {
    const raw = extractTypedValue(v);
    const encrypted = await encryptValue(key, raw);
    result[k] = { String: encrypted };
  }
  return result;
}

/**
 * Decrypt all __cenc_v1_ values found in query response rows.
 * Non-encrypted values pass through unchanged.
 */
export async function decryptResponseRows(
  key: CryptoKey,
  rows: Record<string, unknown>[],
): Promise<Record<string, unknown>[]> {
  const decrypted: Record<string, unknown>[] = [];

  for (const row of rows) {
    const newRow: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(row)) {
      const raw = extractTypedValue(v);
      if (typeof raw === "string" && raw.startsWith(CENC_PREFIX)) {
        newRow[k] = await decryptValue(key, raw);
      } else {
        newRow[k] = v;
      }
    }
    decrypted.push(newRow);
  }

  return decrypted;
}

/** Check if a string is client-encrypted */
export function isClientEncrypted(value: string): boolean {
  return value.startsWith(CENC_PREFIX);
}
